[package]
name = "todo-or-die-providers"
version = "0.2.1"
edition.workspace = true

[dependencies]
todo-or-die-core = { path = "../todo-or-die-core" }
reqwest.workspace = true
serde.workspace = true
thiserror.workspace = true
urlencoding.workspace = true
serde_json.workspace = true
semver.workspace = true
tokio.workspace = true
rustls.workspace = true

[dev-dependencies]
wiremock = "0.6"
